---
- name: Install Nginx
  hosts: all
  become: yes
  tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install Nginx package
      yum:
        name: nginx
        state: latest

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
