---
- name: Uninstall Nginx
  hosts: all
  become: yes
  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped

    - name: Remove Nginx package
      yum:
        name: nginx
        state: absent

