---
- name: Install Zabbix 4.0
  hosts: all
  become: yes
  tasks:

    - name: Install epel-release package
      yum:
        name: epel-release
        state: present

    - name: Remove all Zabbix 
      command: yum remove -y 'zabbix*'

    - name: Clean Yum Cache
      command: yum clean all


    - name: Install Zabbix agent package
      yum:
        name: zabbix40-agent
        state: present
